celo-org/react-celo

packages/use-contractkit/src/dappkit-wallet/linking.ts

Short term fix, closes celo-org/celo-monorepo#7486 until we can move this -> dappkit-web (after [this PR](https://github.com/celo-org/celo-monorepo/pull/7484))
- timeout + redirect fix for detecting if app is installed does not work in newer versions of iOS (always redirects to app store regardless of whether Valora is installed or not)
- simple fix should work on iOS + android

Simplify openURL

---

packages/example/next-env.d.ts
packages/example/pages/_app.tsx
packages/use-contractkit/src/connectors/connectors.ts
packages/use-contractkit/src/contract-kit-reducer.ts

There was a bug recently which caused Valora tu return the account address of users instead of the wallet address. There's a PR to fix this [in Valora's repo](https://github.com/valora-inc/wallet/pull/1074) but we still need to handle this case for users running older versions of the app. This PR tries to call the Accounts contract to map to wallet address in case the address returned has a wallet address linked.
Aside from that, fixed two small other issues:
- Open the deeplink in the same tab, not another one. Popups are blocked with Safari so this wasn't working.
- Sometimes the text string 'undefined' was being stored in localStorage. I added a check in one place but we still need to make sure it's not happening elsewhere.

Map Valora's returned address to wallet address

---

packages/use-contractkit/src/ethers.ts

Without this ether js JsonRPC provider seems to call a detectNetwork Function every event loop which makes a call the node like  {method: eth_ChainID, params: [], id: randomNumber()}

Explicitly add the chain Id to the JSONRPCPROVIDER

---

packages/example/pages/index.tsx
packages/use-contractkit/src/use-contract-kit-methods.ts
packages/use-contractkit/src/use-contractkit.tsx

Have updateNetwork correctly typed to return a Promise (as it's async) and have it throw on failure so UIs can observe and react.
**THIS IS A POSSIBLY SMALL BREAKING CHANGE**
Users of updateNetwork that also have a lint rule to forbid hanging promises will need to await or catch

Fix promise typing for updateNetwork

---

packages/example/pages/index.tsx
packages/use-contractkit/src/connectors/connectors.ts
packages/use-contractkit/src/connectors/useMetaMaskConnector.ts
packages/use-contractkit/src/connectors/useWalletConnectConnector.ts
packages/use-contractkit/src/contract-kit-provider.tsx
packages/use-contractkit/src/contract-kit-reducer.ts
packages/use-contractkit/src/screens/cew.tsx
packages/use-contractkit/src/screens/ledger.tsx
packages/use-contractkit/src/screens/private-key.tsx
packages/use-contractkit/src/types.ts
packages/use-contractkit/src/use-contract-kit-methods.ts
packages/use-contractkit/src/use-contractkit.tsx
readme.md

- fix a bug where changing network in metamask doesn't refresh the contractKit object
- add configurable feeCurrency

change kit on network switch and add feeCurrency to the provider

---

packages/example/package.json
packages/use-contractkit/package.json
packages/use-contractkit/src/connectors/useWalletConnectConnector.ts
packages/use-contractkit/src/utils/useWalletVersion.ts
packages/wallet-walletconnect/package.json
packages/wallet-walletconnect/scripts/run-in-memory-client.ts
packages/wallet-walletconnect/src/constants.ts
packages/wallet-walletconnect/src/wc-wallet.ts
packages/walletconnect-v1/package.json
packages/walletconnect-v1/src/constants.ts
packages/walletconnect-v1/src/wc-wallet.ts

- Fix WC v2 init blocking issue
- Use 2.1.2-dev versions throughout packages
- Update relayUrl to match WalletConnect's default settings

fix: Avoid blocking during WC v2 init

---

packages/wallet-walletconnect/package.json
packages/walletconnect-v1/package.json

quick fixes to make the `make dev` command work again
also, remove unnecessary dependency in walletconnect-v1

Fix makefile

---

packages/example/package.json
packages/use-contractkit/package.json
packages/wallet-walletconnect/package.json
packages/wallet-walletconnect/src/test/common.ts
readme.md
yarn.lock

This could be part of the final 3.0.0 release as it's a breaking change to the API
Now consumers of UCK should install @celo/contractkit in their own dependencies
[Closes #92]
Edit: I also took the opportunity to cherry-pick dependabot's PRs (#100 and #98) in here

feat: move @celo/contractkit from dependencies to peerDeps

---

packages/example/pages/index.tsx
packages/use-contractkit/src/connectors/useMetaMaskConnector.ts
packages/use-contractkit/src/utils/metamask.ts

while cREAL is supported out of the box now it 
* shows cREAL balance in the example app
* will show balance of any new stable added to contract kit
* will add cREAL to MetaMask when asked 
* deduplicates 2 interfaces

improve cREAL/cStable Support

---

packages/use-contractkit/src/connectors/connectors.ts
packages/use-contractkit/src/types.ts
packages/use-contractkit/src/use-contract-kit-methods.ts

When in mobile context and connected to a wallet that uses deeplinks auto switch to that wallet app.
fixes #108

Auto Switch to Valora (or other deeplinked wallet) when signing/approving on mobile

---

packages/wallet-walletconnect/src/utils/parse-addresses.ts
packages/walletconnect-v1/src/utils/parse-addresses.ts

Everywhere else we are importing celo/utils specific folders and functions. Thought it would be good to be consistent.
I believe this might make it more likely for bundle size to be kept down as just the used functions are imported.

Precise celo/utils imports 

---

packages/use-contractkit/src/screens/valora.tsx

Add A clickable link for situations where the mobile web browser wont open deeplinks.
When using Opera we run into a situation where using javascript to open up a deep link does not work. Since auto open is not possible add a small link to Open Valora. 
fixes #82

fix Some Mobile Browsers are not Auto Opening Valora

---

packages/use-contractkit/src/contract-kit-provider.tsx
packages/use-contractkit/src/utils/helpers.ts

Rather than finding in DEFAULT_NETWORKS instead look in passed networks array. 
fixes https://github.com/celo-org/use-contractkit/issues/134
Note this does require the networks passed into ContractKitProvider to be consistent

Fix bug where passing in custom rpc url got reset

---

.github/labeler.yml
.github/workflows/label.yml

Any time an issue is created it will be given the Applications Label. 
This means it will showup in the zenhub board which filters by label due to monorepo

chore: Label all issues in repo as Applications so they show in zenhub

---

packages/example/pages/_app.tsx
packages/example/pages/index.tsx
packages/use-contractkit/src/connectors/connectors.ts
packages/use-contractkit/src/constants.tsx
packages/use-contractkit/src/types.ts
packages/use-contractkit/src/use-contract-kit-methods.ts
packages/use-contractkit/src/use-contractkit.tsx
packages/use-contractkit/src/utils/helpers.ts
packages/use-contractkit/src/utils/metamask.ts
readme.md

- add passed networks as a return value of useContractKit
- replace NetWorkNames Enum with POJO so that its extendable
- Make Network interface support arbitrary networks and include option to pass in the nativeCurrency which is used when adding to metamask.
- For non celo networks dont try to add celo tokens to metamask
- fix: updateFeeCurrency should only be an option for Connectors / wallets that support alternative  gas fee currencies

FEAT: Allow developers to pass in any networks they wish (and fix feeCurrency)

---

packages/use-contractkit/src/constants.tsx

For the Metamask Supported Provider install URL, if on mobile, append the current browser location to `https://metamask.app.link/dapp/`

Append current browser location in Metamask mobile

---

packages/example/pages/index.tsx

Fix #146 #178
StableTokenBRL not currently deployed to Baklava, and was receiving `Error: StableTokenBRL not (yet) registered` on the sample app. This change catches the UnregisteredError and shows "not deployed in network" under the token balances.

Fix StableTokenBRL error: Catch token not registered error, display non-deployed token in balances

---

tsconfig.json

All major browsers support es6 and this should improve bundle size too.
https://www.typescriptlang.org/tsconfig#target

move to target es6

---

package.json
packages/react-celo/__tests__/connectors/ledger.test.ts
packages/react-celo/__tests__/connectors/metamask.test.ts
packages/react-celo/__tests__/connectors/private-key.test.ts
packages/react-celo/__tests__/connectors/walletconnect.test.ts
packages/react-celo/__tests__/react-celo-provider.tsx
packages/react-celo/src/connectors/connectors.ts
yarn.lock

use `eth-testing` library to test Metamask connector (as such its the best tested
unfortunately that library not working for testing our other Connectors. 
when connecting via MetaMask changes the default account to be obtained via `ethereum.request({
method: 'eth_requestAccounts',
});
` 
rather than `this.kit.connection.web3.eth.getAccounts();`
changed updateKitWithNetwork as it was not working like i would expect
fixes #177

Connector Testing 

---

packages/react-celo/src/react-celo-provider.tsx
packages/react-celo/src/use-celo.tsx

add useContrakit == useCelo and ContractKitProvider == CeloProvider back so its simpler to upgrade to v4

Add Aliases for old function names 

---

packages/example/components/test-plan/connect-wallet.tsx
packages/example/components/test-plan/error-icon.tsx
packages/example/components/test-plan/send-transaction.tsx
packages/example/components/test-plan/success-icon.tsx
packages/example/components/test-plan/switch-networks.tsx
packages/example/components/test-plan/ui.tsx
packages/example/components/test-plan/update-fee-currency.tsx
packages/example/components/test-plan/useDisabledTest.tsx
packages/example/components/test-plan/useTestStatus.tsx
packages/example/pages/_app.tsx
packages/example/pages/index.tsx
packages/example/pages/wallet-test-plan.tsx
packages/example/pages/wallet.tsx
packages/example/styles/global.css
packages/example/utils/send-test-transaction.ts
packages/example/utils/send-transaction.ts

This addresses #164 
Following the draft PR https://github.com/celo-org/use-contractkit/pull/200, this PR adds a page to the Example app where the user can go through a set of steps to check how well a wallet interacts with the available actions from `react-celo`.
There are more tests to be added, but to avoid a huge PR, I'm opening this to merge these first ones.
I've simplified the UI a bit (compared to the Draft PR) to make it leaner and more consistent.
- Calling `destroy` for some reason doesn't update the `address` returned by `useCelo`. This means, if you click on it, you'll need to refresh the page to see the test reset.
- Even though the provider is set to Mainnet, if you change the network to Alfajores, then refresh the page, it will still be set to Alfajores - not sure if this …

feat: wallet test plan page

---

packages/react-celo/src/index.ts

While going over the list of checks for `v4.0`, I noticed I couldn't use `useContractKit` .
I got the error:  `Module '"@celo/react-celo"' has no exported member 'useContractKit'.ts(2305)`
Adding it to the export in `react-celo/src/index.ts` fixed it.

fix: export useContractKit

---

packages/react-celo/src/connectors/connectors.ts
packages/react-celo/src/connectors/useWalletConnectConnector.ts
packages/react-celo/src/constants.tsx
packages/react-celo/src/screens/wallet-connect.tsx
packages/react-celo/src/types.ts
packages/react-celo/src/use-celo-methods.ts

This makes the rendering of the desktop buttons a bit more flexible via `supportedPlatforms`. This refactor also allows CeloTerminal to be displayed adequately.
Fix #212

refactor: deeplinks and weblinks logic

---

packages/example/components/test-plan/disconnect-button.tsx
packages/example/pages/_app.tsx
packages/example/pages/wallet-test-plan.tsx

Disclaimer: there was nothing "wrong" with `destroy` per se, but the `wallet-test-plan` page was calling it outside of its provider.
The reason why this even worked at all is because the whole app is surrounded by a provider, i removed that to make sure we don't run into the error again.
fix #206

fix: destroy not re-rendering

---

packages/example/components/theme-button.tsx
packages/example/pages/index.tsx
packages/react-celo/src/use-celo-methods.ts
packages/react-celo/src/use-celo.tsx

Since the reducer state can take null I updated the `updateTheme` method to accept null. Also, I made it so you could turn off the themes in the example.

Allow updateTheme to take a null value

---

jest.config.js
packages/example/components/test-plan/connect-wallet.test.tsx
packages/example/components/test-plan/connect-wallet.tsx
packages/example/components/test-plan/ui.tsx
packages/example/jest.config.js
packages/example/package.json
packages/example/tsconfig.json
packages/example/tsconfig.spec.json

Sets up tests in the example app, using the configuration from the root (modified only to accept `.test` files outside of `__tests__`).
Part of #164

chore: configure test in example app

---

packages/react-celo/src/react-celo-reducer.ts
packages/react-celo/src/types.ts
packages/react-celo/src/use-celo-methods.ts
packages/react-celo/src/use-celo.tsx

I noticed we were typing the same types in 3 different places, in the implementation, in the exported types (i.e.: in `CeloMethods`) and then again in `useCelo`. 
The main change is in `packages/react-celo/src/use-celo.tsx`.
This PR focuses on the `useCelo` bit only and the intent is to reuse the existing types in order to:
- avoid repetition
- move documentation closer to where the implementation is
- make it easier to understand where everything that gets returned in `useCelo` is coming from
**Other changes**
- Added a bit more documentation in some of the Celo methods since I had moved other things there.

refactor(useCelo types): make it explicit where types are coming from

---

packages/walletconnect-v1/__tests__/utils/common.ts
packages/walletconnect-v1/jest.config.js
packages/walletconnect-v1/package.json
packages/walletconnect-v1/src/utils/from-rpc-sig.test.ts
packages/walletconnect-v1/src/utils/from-rpc-sig.ts
packages/walletconnect-v1/src/utils/fromRPCsig.ts
packages/walletconnect-v1/src/wc-signer.ts

ethereumjs-util was only used in 2 places. 
remove by using equivalent function from wallet connect and inlining ethereumjs-utils `fromRPCsig` with some modifications. for instance original took many types, in this case we only accept a string as input.

remove ethereumjs utils

---

packages/example/package.json
packages/react-celo/package.json

Dependency was listed in wrong package

fix: Celo Utils is not used in react-celo, only in the example app

---

.yarnrc
development.md
package.json
readme.md
yarn.lock

Addresses #232 
Introduces the `@clabs/packages-publisher` so we can start testing it for publishing packages. Note that the tool is in alpha because I think we need to use it a couple of times and check where it fails.
Bear in mind that the tool expects the versions to NOT contain `dev` suffix, so before publishing, you'll need to run the `bump-versions` tool. 
Then, to add back `dev` in the version, you'll need to run the `bump-versions` again, but this time forcing `dev` to be used:
```
yarn cli:dev-run bump-versions prerelease --preId dev --forcePreId
```
I think it'd be useful to agree on whether we'll continue to use `dev` in the version or not, and what's the ideal workflow. As I mentioned, I think we should drop `dev` and use regular semver versioning. If we want to split `dev` vs …

feat: add packages publisher

---

packages/react-celo/__tests__/connectors/ledger.test.ts
packages/react-celo/__tests__/connectors/metamask.test.ts
packages/react-celo/__tests__/connectors/private-key.test.ts
packages/react-celo/__tests__/utils/react-celo-reducer.test.ts
packages/react-celo/src/connectors/connectors.ts
packages/react-celo/src/constants.tsx
packages/react-celo/src/react-celo-reducer.ts
packages/react-celo/src/use-celo-methods.ts
packages/react-celo/src/utils/clearPreviousConfig.ts
packages/react-celo/src/utils/helpers.ts
packages/react-celo/src/utils/localStorage.test.ts
packages/react-celo/src/utils/localStorage.ts
packages/react-celo/src/utils/useProviders.ts
packages/walletconnect-v1/src/wc-wallet.ts

Use specific getter and setter functions for accessing local storage rather than calling directly. this allows for us to type the input and output and do serialization in one spot. 
Fixes #252

Typed Local Storage

---

packages/react-celo/__tests__/react-celo-provider.test.tsx
packages/react-celo/src/react-celo-provider.tsx

add defaultNetworkProp
allow both for now. and favor network so that this is a nonbreaking change
unless you count that this fixes passing in a unfindable network now throws an error instead of silently defaulting to main-net

fixes #203 deprecated network prop

---

packages/react-celo/src/modals/action.tsx
packages/react-celo/src/modals/connect.tsx
packages/react-celo/src/utils/helpers.ts

Fixes #202
Previously, background could be scrolled while modal is open. This PR disables it for the connect modal and action modal.

When Modal is Open Dont Allow Background to scroll 

---

packages/react-celo/src/modals/action.tsx
packages/react-celo/src/modals/connect.tsx
packages/react-celo/src/styles.css

previously to fix an issue on iOS with modal height we added -webkit-fill-available to html. however this causes gradient backgrounds with no repeat set to end at the window height rather than extend down the desktop. 
THE SOLUTION
use react modals custom classname to add the styles to html and body only when our modal is open
fixes. #268

Fixes some external issues with styles being set on elements 

---

.github/workflows/ci.yml
packages/react-celo/__tests__/modals/connect.test.tsx
packages/react-celo/__tests__/react-celo-provider.test.tsx
packages/react-celo/__tests__/render-in-provider.tsx
packages/react-celo/package.json
packages/react-celo/src/modals/connect.tsx

Ensures that apps can pass in a z-index to the overlay to ensure the modal is placed above their elements. 
Also makesure they cant pass in onRequestClose as that would break our functionality

Fix handling of reactModalProp

---

packages/react-celo/src/styles.css

4.0.0 taildinwo base was introduced. 
This resets various global styles. We should not do this as it messes styles of dapps that use the package. 
Also remove various styles that were specific to react-celo but really not needed. 
see #268 (https://github.com/celo-org/react-celo/issues/268#issuecomment-1165850022)

Remove Extra Global Styles

---

jest.config.js
packages/react-celo/__tests__/connectors/coinbase-wallet.test.ts
packages/react-celo/__tests__/utils/resurector.test.ts
packages/react-celo/package.json
packages/react-celo/src/components/icons/coinbase-wallet.tsx
packages/react-celo/src/components/icons/index.tsx
packages/react-celo/src/connectors/coinbase-wallet.ts
packages/react-celo/src/connectors/connectors-by-name.ts
packages/react-celo/src/connectors/index.ts
packages/react-celo/src/constants.tsx
packages/react-celo/src/hooks/use-coinbase-wallet-connector.ts
packages/react-celo/src/screens/coinbase.tsx
packages/react-celo/src/screens/index.ts
packages/react-celo/src/utils/resurrector.ts
yarn.lock

Add support for Coinbase wallet extension and mobile.
* Add @coinbase/wallet-sdk
* Add Coinbase wallet connector, Coinbase connection screen, and Coinbase wallet logo

Add coinbase wallet support

---

packages/example/components/buttons.tsx
packages/example/components/test-plan/disconnect-button.tsx
packages/example/components/test-plan/ui.tsx
packages/example/components/theme-button.tsx
packages/example/pages/_app.tsx
packages/example/pages/index.tsx
packages/example/pages/wallet-test-plan.tsx
packages/example/pages/wallet.tsx
packages/example/styles/global.css
packages/example/tailwind.config.js

Adds nice colors, and use a more showcase like layout 
fixes #258

New Look for Demo Site

---

packages/react-celo/src/components/tray.tsx
packages/react-celo/src/modals/connect.tsx
packages/react-celo/src/styles.css

Fix background gradient while modal open (avoid setting min-height on body for desktop sizes)
Fix list of wallets hiding last wallet on ios (now has extra bottom padding)
Fix default stacking order being too low  (now zIndex is 40) this can also be [modified](https://github.com/celo-org/react-celo/discussions/292)

Fix style bugs

---

packages/react-celo/src/connectors/injected.ts
packages/react-celo/src/global.d.ts

When a user locks their metamask it emits the accountsChanged event with an empty array. 
Previously this was causing react-celo to error and improperly disconnect. 
Now it handles disconnecting with grace. 
This mirrors behavior seen on daps such as uniswap and on the rainbowkit. 
also adjusts the Ethereum object to have some properties missing from the type

Fix improper error when metamask gets locked

---

packages/react-celo/__tests__/utils/metamask.test.ts
packages/react-celo/src/connectors/coinbase-wallet.ts
packages/react-celo/src/connectors/injected.ts
packages/react-celo/src/global.d.ts
packages/react-celo/src/utils/metamask.ts

Returns back behavior of switching metamask to dapp's default network on initialise. This was accidentally broken by refactor. 
note that  in future another version may make this behavior optional but not not so as of yet. 
* also fix token import to metamask to use new mento uri for logo
* change function name to be generic rather than specific to celo.

Fix regression  metamask network regression

---

packages/react-celo/__tests__/utils/local-storage.test.ts
packages/react-celo/__tests__/utils/persistor.test.ts
packages/react-celo/src/components/icons/index.tsx
packages/react-celo/src/constants.tsx
packages/react-celo/src/hooks/use-providers.ts
packages/react-celo/src/utils/local-storage.ts
packages/react-celo/src/utils/persistor.ts

Rather than just remembering the most recent wallet remember the last 3. 
* three could be any number but seems a good medium between a long memory and just taking over the entire list
* list never duplicates wallets, and most recent is pulled to top if it was used already recently

Feat #294 show up to 3 most recent wallets used

---

packages/react-celo/src/connectors/injected.ts
packages/react-celo/src/global.d.ts
packages/react-celo/src/react-celo-provider.tsx
packages/react-celo/src/types.ts
packages/react-celo/src/use-celo-methods.ts

When resurrecting metaMask and metaMask locked dont request the account (instead use the address found in local storage). This stops the need to unlock metaMask right away when loading the site. 
Fixes #295

dont ask metamask to unlock if we are already connected and ressurecting

---

packages/example/package.json
packages/react-celo/package.json
packages/walletconnect/package.json
yarn.lock

I noticed `@celo/wallet-walletconnect@5.0.2` pulled by `@celo/react-celo@5.0.2` depends on celo SDK `^2.2.0` leading to duplicate packages in the final bundle if celo SDK v3 is already present.
```
"@celo/wallet-walletconnect@5.0.2":
version "5.0.2"
resolved "https://registry.yarnpkg.com/@celo/wallet-walletconnect/-/wallet-walletconnect-5.0.2.tgz#14d8fff7c232578977878f2ea2c552fe5df06b70"
integrity sha512-CK6hGfYgrqC9iHAJvauofs9U3RdEqIZ16fm/95fgso0OMe1i8Gn9v/TNPpM2cuIY9/58zZshgHKqCAODzH8ukg==
dependencies:
"@celo/connect" "^2.2.0"
"@celo/utils" "^2.2.0"
"@celo/wallet-base" "^2.2.0"
"@celo/wallet-remote" "^2.2.0"
"@walletconnect/auth-client" "^2.0.2"
"@walletconnect/sign-client" "^2.3.2"
"@walletconnect/types" "^2.3.2"
"@walletconnect/utils" "^2.3.2"
debug "^4.3.3"
ethereumjs-util "^7.1.3" …
```

Allow celo SDK v2 or v3 for `@celo/wallet-walletconnect`
