celo-org/react-celo

packages/use-contractkit/src/modals/connect.tsx
literally just using provider name as a key to avoid react warning
=> remove annoying react warning about key

readme.md
There is a variable in the snippet that is not defined and this is causing the app to crash on using this code. A minor change should fix this issue
=> removed undefined variable usage

packages/use-contractkit/src/connectors/connectors.ts
Follow up to https://github.com/celo-tools/use-contractkit/pull/27
Tested with both verified and unverified accounts in Safari & Chrome.
See https://valora-app.slack.com/archives/C01D6H6116V/p1630542810004200 and https://celo-org.slack.com/archives/C014SRL4URY/p1630620520037400?thread_ts=1630594970.032600&cid=C014SRL4URY for more context
=> Fix the fetching of wallet address for accounts

packages/use-contractkit/src/connectors/useMetaMaskConnector.ts, packages/use-contractkit/src/constants.tsx, packages/use-contractkit/src/screens/index.ts, packages/use-contractkit/src/screens/metamask.tsx
- add code to differentiate between metamask and other web3 injections.
- fix bug where injected web3 wasn't appearing in connect options.
=> fix: fix bug where injected web3 wasn't appearing in connect modal

packages/example/pages/_app.tsx, packages/use-contractkit/package.json, packages/use-contractkit/src/components/ProviderSelect.tsx, packages/use-contractkit/src/connectors/useWalletConnectConnector.ts, packages/use-contractkit/src/modals/connect.tsx, packages/use-contractkit/src/screens/wallet-connect-custom.tsx, packages/use-contractkit/src/types.ts, packages/use-contractkit/src/utils/fetchWCWallets.ts, packages/use-contractkit/src/utils/sort.ts, packages/use-contractkit/src/utils/useWalletVersion.ts, readme.md, yarn.lock
[Blocked by #71] Since the first iteration of custom wallets are WC compatible wallets.
Working on having completely custom providers too.
=> Feat configure wallets

packages/example/pages/index.tsx
This should fix #55 
[Closes #55]
=> fix: add a gasPrice to the example transfer

readme.md
=> Tell People to use Github Discussions for Support

packages/example/pages/index.tsx, packages/use-contractkit/src/connectors/connectors.ts, packages/use-contractkit/src/connectors/useWalletConnectConnector.ts, packages/use-contractkit/src/constants.tsx, packages/use-contractkit/src/contract-kit-provider.tsx, packages/use-contractkit/src/contract-kit-reducer.ts, packages/use-contractkit/src/use-contract-kit-methods.ts, packages/use-contractkit/src/use-contractkit.tsx, packages/use-contractkit/src/utils/helpers.ts
Fixes https://github.com/celo-org/use-contractkit/issues/90
=> fix: More explicit storage of feeCurrency field

packages/example/package.json, packages/use-contractkit/package.json, packages/wallet-walletconnect/package.json, packages/walletconnect-v1/package.json, yarn.lock
Moving out of 3.0.0 beta.
Upgraded @celo packages.
=> chore: Move to 3.0.0

scripts/publish-packages.ts
[Related to celo-org/celo-monorepo#9394]
=> chore: add prerelease checks to the deploy script

readme.md
Fixes a couple of small errors I found while reading the README.
=> docs: small readme fixes

package.json, readme.md
its hard to remember to run make dev 
`yarn dev` is more common
=> chore: make it easier to run dev mode

packages/example/pages/_app.tsx, packages/use-contractkit/src/constants.tsx, packages/use-contractkit/src/modals/connect.tsx, packages/use-contractkit/src/screens/wallet-connect-custom.tsx, packages/use-contractkit/src/types.ts, packages/use-contractkit/src/utils/sort.ts, readme.md
extracted logic decoupled from the registry from #76
=> feat: add modal customization options

packages/example/package.json, packages/use-contractkit/package.json, packages/use-contractkit/src/use-contract-kit-methods.ts, packages/wallet-walletconnect/package.json, packages/walletconnect-v1/package.json, readme.md, yarn.lock
=> Use CK 3.1 release

.github/workflows/label.yml, packages/example/pages/_app.tsx, readme.md
Addresses items raised in #181 and also adds a bit of instruction for running it locally. 
It also attempts to fix the [issue labeler error](https://github.com/celo-org/use-contractkit/actions/runs/2333118394).
=> docs: improve readme

packages/example/styles/global.css
=> fix: remove toggle z-index to not interfere with the modal

readme.md
Remove unneeded info from README regarding wallet actions.
=> fix: remove specific actions from wallet

packages/example/pages/index.tsx, packages/react-celo/package.json, packages/react-celo/src/components/connector-screen.tsx, packages/react-celo/src/components/ios-viewport-fix.tsx, packages/react-celo/src/components/modal-container.tsx, packages/react-celo/src/components/tray.tsx, packages/react-celo/src/constants.tsx, packages/react-celo/src/modals/action.tsx, packages/react-celo/src/react-celo-provider.tsx, packages/react-celo/src/screens/metamask.tsx, packages/react-celo/src/styles.css, yarn.lock
This solves two issues:
- on mobile the search bar at the bottom wasn't ideal
- on safari, 100vh isn't well supported [without a couple hacks](https://allthingssmitty.com/2020/05/11/css-fix-for-100vh-in-mobile-webkit/)
- fix #187 
Thanks @aaronmgdr for discovering this!
=> fix: adjust styles for mobile and specifically for ios safari

packages/example/package.json, packages/react-celo/package.json
When i published this didnt get updated
=> fix example app dependencies

packages/react-celo/src/react-celo-provider.tsx
This is the initial state for reducer but didnt have that explicit type.
=> fix add proper Type for initialState

packages/example/components/theme-button.tsx, packages/react-celo/__tests__/react-celo-provider.test.tsx, packages/react-celo/__tests__/utils/colors.test.ts, packages/react-celo/src/modals/action.tsx, packages/react-celo/src/modals/connect.tsx, packages/react-celo/src/use-celo-methods.ts, packages/react-celo/src/utils/colors.ts, packages/react-celo/src/utils/helpers.ts
=> feat: a11y/colors

packages/react-celo/__tests__/utils/persistor.test.ts, packages/react-celo/__tests__/utils/resurector.test.ts, packages/react-celo/__tests__/utils/updater.test.ts, packages/react-celo/package.json, packages/react-celo/src/connectors/common.ts, packages/react-celo/src/connectors/wallet-connect.ts, packages/react-celo/src/constants.tsx, packages/react-celo/src/hooks/use-wallet-connect-connector.ts, packages/react-celo/src/screens/placeholder.tsx, packages/react-celo/src/screens/private-key.tsx, packages/react-celo/src/utils/local-storage.ts, packages/react-celo/src/utils/persistor.ts, packages/react-celo/src/utils/resurrector.ts, packages/react-celo/src/utils/updater.ts, yarn.lock
[based off the bestselling novel ](https://docs.google.com/document/d/10guYFad1C5Yc4nC8BYcUSOh2REn_BJJ6HXbv3e5DHoc/edit#) this PR creates the listeners that will respond when Connectors emit events. 
It does not yet touch connectors apart from creating an AbstractConnector they will inherit from
=> New Internals for RC

packages/react-celo/__tests__/react-celo-provider.test.tsx, packages/react-celo/src/modals/connect.tsx, packages/react-celo/src/utils/useProviders.ts
Passing in the `hideFromDefaults` option was having no effect on what was showing. 
fixes #274
=> Fix (hide from defaults not hiding wallets)

packages/example/package.json, packages/react-celo/package.json, packages/walletconnect-v1/package.json, yarn.lock
accidentally didnt whitelist this important file
=> fix #320 lib/styles.css missing

packages/example/package.json, packages/react-celo/package.json, packages/walletconnect-v1/package.json
* fix #320 lib/styles.css missing
accidentally didnt whitelist this mportant file
* no dev
=> fix #320 lib/styles.css missing (#321)

packages/example/package.json, packages/react-celo/package.json, packages/walletconnect-v1/package.json, yarn.lock
=> publish 4.3.0

packages/example/package.json, packages/react-celo/package.json, packages/walletconnect/package.json
5.0.1 add  a postinstall script but did not include the file.
=> Fix Missing install script

packages/react-celo/src/screens/wallet-connect.tsx
=> fix: wc register url

packages/react-celo/__tests__/utils/metamask.test.ts, packages/react-celo/src/constants.tsx, packages/react-celo/src/types.ts, packages/react-celo/src/utils/metamask.ts
adds cannoli testnet info
also updates explorer infor for other testnets to use clean urls
=> adds cannoli testnet info

migration-notes.md, readme.md
Official deprecation notice and migration guide.
=> docs: add a migration guide
